const SPEAKERS = [
  {
    name: 'Jina Anne',
    twitter: '@jina',
    website: 'https://www.sushiandrobots.com/',
    location: 'US',
    topics: ['Design Systems', 'Sass', 'Design', 'CSS'],
    languages: ['English'],
    country: 'US',
  },
  {
    name: 'Jennifer Bland',
    twitter: '@ratracegrad',
    website: 'http://www.jenniferbland.com/',
    location: 'Atlanta, GA',
    topics: [
      'Workshop Speeches',
      'JavaScript',
      'Node.js',
      'AngularJS',
      'Angular',
      'Vue',
      'Web Components',
      'Polymer',
      'HTML/CSS',
      'Flexbox',
    ],
    languages: ['English'],
    country: 'US',
  },
  {
    name: 'Lin Clark',
    twitter: '@linclark',
    website: '',
    location: 'US',
    topics: ['JavaScript', 'React', 'Flux', 'Relay', 'Redux', 'WebAssembly'],
    languages: ['English'],
    country: 'US',
  },
  {
    name: 'Chloe Condon',
    twitter: '@chloecondon',
    website: 'https://medium.com/@chloecondon',
    location: 'Bay Area / San Francisco',
    topics: ['Developer Evangelism', 'Docker'],
    languages: ['English'],
    country: 'US',
  },
  {
    name: 'Kim Crayton',
    twitter: '@KimCrayton1',
    website: 'http://kimcrayton.com/',
    location: 'Atlanta, GA, USA',
    topics: ['Diversity', 'Mentoring', 'Women in Tech'],
    languages: ['English'],
    country: 'US',
  },
  {
    name: 'Santina Croniser',
    twitter: '@SantinaCroniser',
    website: '',
    location: 'Chicago, IL',
    topics: [
      'Accessibility',
      'Diversity',
      'Women in Tech',
      'Frontend Development',
      'CMS',
      'Tech in Higher Education',
    ],
    languages: ['English'],
    country: 'US',
  },
  {
    name: 'Jen Looper',
    twitter: '@jenlooper',
    website: 'http://www.ladeezfirstmedia.com/',
    location: 'Boston, MA',
    topics: [
      'Keynote Speeches',
      'JavaScript',
      'NativeScript',
      'Web and Mobile Development',
      'IOT',
      'Machine Learning',
    ],
    languages: ['English', 'French'],
    country: 'US',
  },
];

export default SPEAKERS;
